version: "3"

services:

  app: # Имя сервиса
    build:
      context: .
      dockerfile: Dockerfile
    ports: # Проброс портов
      - "8081:8081"
    depends_on:
      - redis

  redis:
    image: redis:latest